export default class SettingsKey {

  static MIN_GROUP_MEMBERS_COUNT = "MIN_GROUP_MEMBERS_COUNT"
  static MAX_GROUP_MEMBERS_COUNT = "MAX_GROUP_MEMBERS_COUNT"
  static LAST_INVITED_GROUP_MEMBERS_DATE = "LAST_INVITED_GROUP_MEMBERS_DATE"
}
